---
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./
  cloudflare:
    class: octodns.provider.cloudflare.CloudflareProvider
    email: zach@hackclub.com
    token: env/CLOUDFLARE_API_KEY

zones:
  eaya.io.:
    sources:
      - config
    targets:
      - cloudflare
